name: Job Report

on:
    schedule:
        - cron: '30 12 * * 1'

    workflow_dispatch:

jobs:
    run-researcher:
        runs-on: ubuntu-latest
        environment: research-service
        env:
            EMAIL_USER: ${{ secrets.EMAIL_USER }}
            EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
            EMAIL_TO: ${{ secrets.EMAIL_TO }}
            NAME_USER: ${{ secrets.NAME_USER }}
            NAME_TO: ${{ secrets.NAME_TO }}
            ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
            BRAVE_SEARCH_API_KEY: ${{ secrets.BRAVE_SEARCH_API_KEY }}
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
              python-version: "3.11"
          - run: cd server && pip install -r requirements.txt
          - name: Run job report
            env:
              EMAIL_USER: ${{ secrets.EMAIL_USER }}
              EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
              EMAIL_TO:   ${{ secrets.EMAIL_TO }}
              NAME_USER:  ${{ secrets.NAME_USER }}  
              NAME_TO:    ${{ secrets.NAME_TO }}     
              ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
              BRAVE_SEARCH_API_KEY: ${{ secrets.BRAVE_SEARCH_API_KEY }}
            run: python server/job-report.py