name: Job Report

on:
    schedule:
        - cron: '30 12 * * 1'

    workflow_dispatch:

jobs:
    run-researcher:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.11"
            
            - name: Change to server directory
              run: cd ./server
            
            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Run orchestrator
              env:
                EMAIL_USER: ${{ secrets.EMAIL_USER }}
                EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
                EMAIL_TO: ${{ secrets.EMAIL_TO }}
                NAME_USER: ${{ secrets.NAME_USER}}
                NAME_TO: ${{ secrets.NAME_TO }}
              run: python job-report.py