name: Job Report

on:
    schedule:
        - cron: '30 12 * * 1'

    workflow_dispatch:

jobs:
    run-researcher:
        runs-on: ubuntu-latest
        env:
            EMAIL_USER: ${{ secrets.EMAIL_USER }}
            EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
            EMAIL_TO: ${{ secrets.EMAIL_TO }}
            NAME_USER: ${{ secrets.NAME_USER }}
            NAME_TO: ${{ secrets.NAME_TO }}
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
              python-version: "3.11"
          - run: cd server && pip install -r requirements.txt
          - name: Run scraper
            env:
              EMAIL_USER: ${{ secrets.EMAIL_USER }}
              EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
              EMAIL_TO:   ${{ secrets.EMAIL_TO }}
              NAME_USER:  ${{ secrets.NAME_USER }}   # or vars.NAME_USER if you saved it as a variable
              NAME_TO:    ${{ secrets.NAME_TO }}     # same comment as above
            run: python scrape-fin-data.py